name: CI/CD Node.js Pipeline  # Nom visible du pipeline

on:
  push:            # Déclenche sur push
    branches: [ "main" ]
  pull_request:    # Déclenche sur PR
    branches: [ "main" ]

jobs:
  test:            # Job CI
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Récupère le code source

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20         # Version Node.js

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test              # Si ça échoue -> le job 'test' échoue

  deploy:          # Job CD
    name: Continuous Deployment
    runs-on: ubuntu-latest
    needs: test                   # Ne s'exécute que si 'test' est OK

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./          # dossier à publier (à adapter si besoin)
